ifeval::["{backend}" != "manpage"]
= `racksdb-web` CLI manpage

This section explains all `racksdb-web` command options available. The content
of the page this also available in `racksdb-web(1)` manpage after installation.

endif::[]

:!example-caption:

== Synopsis

[.cli-opt]#*racksdb-web*# `[_OPTIONS_]`

== Options

[.cli-opt]#*-h, --help*#::
  Show this help message and exit.

[.cli-opt]#*-v, --version*#::
  Show RacksDB version number and exit.

[.cli-opt]#*--debug*#::
  Enable debug mode with more messages in output.

[.cli-opt]#*-b, --db*=#[.cli-optval]##_DB_##::
  Path to database. Both files and directories paths are accepted. If the path
  is a directory, all YAML files in this directory are loaded, recursively. If
  the path does not exist, an error is reported. Default value is
  [.path]#`/var/lib/racksdb/`# directory.

[.cli-opt]#*-s, --schema*=#[.cli-optval]##_SCHEMA_##::
  Path to RacksDB schema YAML file. If the file does not exist, an error is
  reported. Default value is [.path]#`/usr/share/racksdb/schema.yml`#.

[.cli-opt]#*-e, --ext*=#[.cli-optval]##_EXT_##::
  Path to optional RacksDB schema extensions. If the file does not exist,
  it is silently ignored by RacksDB. Default value is
  [.path]#`/etc/racksdb/extensions.yml`#.

[.cli-opt]#*--host*=#[.cli-optval]##_HOST_##::
  The hostname to listen for incoming requests. Set to `0.0.0.0` to listen on
  all IP addresses of the host. Default value is `localhost` which restricts
  connections to local host.

[.cli-opt]#*-p, --port*=#[.cli-optval]##_PORT_##::
  TCP port to listen for incoming requests. Default value is 5000.

[.cli-opt]#*--cors*#::
  Enable CORS headers.

[.cli-opt]#*--openapi*#::
  Enable OpenAPI endpoint to retrieve REST API specifications.

== Exit status

*0*::
  `racksdb-web` has processed command with success.

*1*::
  `racksdb-web` encountered an error.
