---
# Define DPI/sizes for which PNG bitmaps versions of SVG diagrams must be
# generated.
diagrams:
  modules/overview/images/racksdb_overview.svg: medium
  modules/overview/images/racksdb_interfaces.svg: medium
