---
# Define DPI/sizes for which PNG bitmaps version of assemblies must be
# generated.
assemblies:
  screenshots.svg:
  - small
# List raw screenshots for which versions with dropped shadow must be generated.
shadowed:
- home.png
- datacenters.png
- rooms.png
- racks.png
- infrastructures.png
- infrastructure.png
- infrastructure_filters.png
